create table if not exists public.telegram_chat_state (
  chat_id bigint primary key,
  active_summary text not null default '',
  preferences jsonb not null default '{}'::jsonb,
  last_summary_at timestamptz,
  last_active_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.telegram_chat_messages (
  id bigint generated by default as identity primary key,
  chat_id bigint not null,
  role text not null check (role in ('user', 'assistant', 'system', 'tool')),
  content text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists telegram_chat_messages_chat_id_created_at_idx
  on public.telegram_chat_messages (chat_id, created_at desc);

create index if not exists telegram_chat_messages_chat_id_role_idx
  on public.telegram_chat_messages (chat_id, role);

create table if not exists public.telegram_chat_summaries (
  chat_id bigint primary key,
  summary text not null default '',
  covers_through timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists telegram_chat_summaries_chat_id_covers_through_idx
  on public.telegram_chat_summaries (chat_id, covers_through desc);
